### ISSUE TITLE
Add TOML config functionality to docs

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/gitbook-kontrol#51]
Now that Kontrol runs can be configured with the TOML file (https://github.com/runtimeverification/kontrol/pull/580), we should add it to the documentation (and, perhaps, prepare some marketing materials for it).

**Comment by Stevengre** [comment]
### Notes
- `kontrol init` will generate a default `kontrol.toml` file.
  - `kontrol init` should detect the situation of the current dir.
- I need provide the same thing as [foundry does](https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options).

**Comment by Stevengre** [comment]
### All Options

The following is a kontrol.toml file with all configuration options set.

```toml
[build.default]
foundry-project-root       = '.'
regen                      = false
rekompile                  = false
verbose                    = false
debug                      = false
require                    = 'lemmas.k'
module-import              = 'TestBase:KONTROL-LEMMAS'
auxiliary-lemmas           = true

[build]

-I 

[prove.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
max-depth                  = 25000
reinit                     = false
cse                        = false
workers                    = 4
failure-information        = true
counterexample-information = true
minimize-proofs            = false
fail-fast                  = true
smt-timeout                = 1000
break-every-step           = false
break-on-jumpi             = false
break-on-calls             = false
break-on-storage           = false
break-on-basic-blocks      = false
break-on-cheatcodes        = false
run-constructor            = false
no-stack-checks            = true

[show.default]
foundry-project-root       = '.'
verbose                    = false
debug                      = false
use-hex-encoding           = false

[view-kcfg.default]
foundry-project-root       = '.'
use-hex-encoding           = false
```
